#application config
app:
  name: tiklab-xpack-ee
  path: ${APP_HOME}
  version: ee

spring:
  profiles:
    active: demo

#web config
server:
  port: 8081

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.10:5432/tiklab_xpack_ee?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: false
  database: tiklab_xpack_ee

eas:
  embbed:
    enable: false
  address: http://eas-ee.demo.tiklab.net

DATA_HOME: /opt/tiklab/xpack_ee


#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#plugin config
plugin.path: ${APP_HOME}/plugin

base:
  url: http://eas-ee.demo.tiklab.net

#rpc
homes:
  address: http://172.11.1.11:8080

#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default


#file
file:
  path: http://file.dev.tiklab.net


repository:
  address: ${DATA_HOME}/repository