#application config
app:
  name: tiklab-xpack-ee
  path: ${APP_HOME}
  version: ee

spring:
  profiles:
    active: dev

#web config
server:
  port: 8081

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_xpack_ee?currentSchema=public&stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: false
  database: tiklab_xpack_ee

DATA_HOME: ${user.home}/tiklab/${app.name}


#eas config
eas:
  embbed:
    enable: true
base:
  url: http://192.168.10.23:3000


#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/data
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 600

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

#plugin config
plugin.path: ${APP_HOME}/plugin

#rpc
homes:
  address: http://192.168.10.7:8080


#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

#file
file:
  path: http://file.dev.tiklab.net


repository:
  address: ${DATA_HOME}/repository
